"""For each persona, generate (history, incoming, target_response) training triples.

The target_response is generated by an "oracle" LLM that DOES know the persona's
hidden style — this is the upper bound the fine-tuned model is evaluated against
(per gpt.md lecturer feedback).

Output: data/synthetic/pairs.jsonl
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))  # repo root, for `from ml.* import`

from ml._llm import chat, gather_with_concurrency  # noqa: E402

INCOMING_PROMPT = """Generate {n} short, varied WhatsApp messages someone might send to a person matching this summary:

{persona_summary}

Mix: questions, plans, small talk, work updates, requests for help, scheduling, sharing links.
Output strictly a JSON array of strings.
"""

ORACLE_PROMPT = """You are role-playing AS the user defined by this persona. Reply EXACTLY as this user would.

Persona (private - never mention or quote):
{persona_json}

Sample of past messages by this user (style reference):
{history_sample}

INCOMING MESSAGE FROM SOMEONE ELSE:
{incoming}

Reply with ONLY the response text the user would send. No labels, no quotes, no commentary.
If, given the persona, the user genuinely would not respond at all, reply with exactly: __SKIP__
"""

PERSONAS = Path(__file__).resolve().parents[1] / "data" / "synthetic" / "personas.jsonl"
HISTORIES = Path(__file__).resolve().parents[1] / "data" / "synthetic" / "histories.jsonl"
OUT = Path(__file__).resolve().parents[1] / "data" / "synthetic" / "pairs.jsonl"


def _extract_json(t: str) -> str:
    t = t.strip()
    if t.startswith("```"):
        t = t.strip("`")
        if "\n" in t:
            t = t.split("\n", 1)[1]
        if t.endswith("```"):
            t = t[:-3]
    return t.strip()


async def gen_incomings(persona: dict, n: int) -> list[str]:
    prompt = INCOMING_PROMPT.format(n=n, persona_summary=persona.get("persona_summary", ""))
    try:
        out = await chat(prompt, temperature=0.95, max_tokens=800)
        data = json.loads(_extract_json(out), strict=False)
        return [str(x) for x in data if str(x).strip()]
    except Exception as e:  # noqa: BLE001 - skip this user's incomings rather than crash the run
        print(f"  skip incomings for {persona.get('user_id')}: {type(e).__name__}: {e}")
        return []


async def gen_target(persona: dict, history_sample: list[str], incoming: str) -> str | None:
    prompt = ORACLE_PROMPT.format(
        persona_json=json.dumps(persona, ensure_ascii=False, indent=2),
        history_sample="\n".join(f"- {h}" for h in history_sample),
        incoming=incoming,
    )
    out = await chat(prompt, temperature=0.7, max_tokens=300)
    out = out.strip().strip('"').strip()
    if not out or out == "__SKIP__":
        return None
    return out


# Bound the number of in-flight oracle calls PER USER. Without this, a user with
# N pairs fires N concurrent calls, and with several users running at once this
# floods the provider rate limit (e.g. Groq) during large generation runs.
_ORACLE_INFLIGHT = int(os.getenv("ORACLE_INFLIGHT", "4"))


async def gen_pairs_for_user(
    persona: dict,
    history: list[str],
    n_pairs: int,
    history_sample_size: int,
    rng: random.Random,
) -> list[dict]:
    if not history:
        return []
    incomings = await gen_incomings(persona, n_pairs)

    sem = asyncio.Semaphore(_ORACLE_INFLIGHT)

    async def make(incoming: str) -> dict | None:
        try:
            async with sem:
                sample = rng.sample(history, k=min(history_sample_size, len(history)))
                target = await gen_target(persona, sample, incoming)
        except Exception as e:  # noqa: BLE001 - e.g. RetryError on rate limit; skip this pair
            print(f"  skip pair for {persona.get('user_id')}: {type(e).__name__}")
            return None
        if not target:
            return None
        return {
            "user_id": persona["user_id"],
            "history": sample,
            "incoming_message": incoming,
            "target_response": target,
        }

    pairs = await asyncio.gather(*(make(i) for i in incomings))
    return [p for p in pairs if p]


async def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pairs-per-user", type=int, default=50)
    p.add_argument("--history-sample", type=int, default=10)
    p.add_argument("--concurrency", type=int, default=4)
    p.add_argument("--seed", type=int, default=42)
    args = p.parse_args()

    if not PERSONAS.exists() or not HISTORIES.exists():
        raise SystemExit("personas.jsonl or histories.jsonl missing - run earlier steps first")

    personas = {p["user_id"]: p for p in (json.loads(l) for l in PERSONAS.read_text(encoding="utf-8").splitlines() if l.strip())}
    histories = {h["user_id"]: h["messages"] for h in (json.loads(l) for l in HISTORIES.read_text(encoding="utf-8").splitlines() if l.strip())}

    rng = random.Random(args.seed)

    coros = [
        gen_pairs_for_user(personas[uid], histories.get(uid, []), args.pairs_per_user, args.history_sample, rng)
        for uid in personas
    ]
    user_pairs = await gather_with_concurrency(coros, args.concurrency)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    with OUT.open("w", encoding="utf-8") as f:
        for batch in user_pairs:
            for row in batch:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")
                total += 1
    print(f"Wrote {total} training pairs → {OUT}")


if __name__ == "__main__":
    asyncio.run(main())
