"""LLM-judge prompts for the Style Indistinguishability Test.

Spec reference: §32 + lecturer feedback. Two responses are presented; the judge
must pick the one written by the actual user. The order of A/B is randomized
upstream by the evaluator (eval/indistinguishability.py).
"""

JUDGE_PROMPT = """You are an expert judge of personal writing style on WhatsApp.

You will be given:
1. A user's chat history (messages they wrote in the past).
2. A new incoming message addressed to the user.
3. Two candidate responses, A and B. Exactly one was written by the actual user; the other was generated by a different model.

Your task: decide which response was MORE LIKELY written by the same user, based on style cues
(length, punctuation, emojis, slang, rhythm, vocabulary, formality, greeting habits).
Ignore which response is "better" or "more correct" - judge ONLY by stylistic resemblance.

[USER'S CHAT HISTORY]
{history}

[INCOMING MESSAGE]
{incoming}

[RESPONSE A]
{response_a}

[RESPONSE B]
{response_b}

Reply with exactly one character: A or B.
"""


RELEVANCE_PROMPT = """Rate how well the response addresses the incoming message on a 1-5 scale.
1 = ignores or contradicts the question
3 = partially relevant
5 = fully addresses it

[INCOMING MESSAGE]
{incoming}

[RESPONSE]
{response}

Reply with a single digit 1-5.
"""
